name: latex-to-release-pdf
description: Create a pdf from latex source

inputs:
  release_url:
    description: Release url to add created pdf to
    required: true
  file_name:
    description: Name of the main latex file
    required: true
  github_token:
    description: GitHub token
    required: true
  repository:
    description: Repository slug name
    required: true

runs:
  using: "composite"
  steps:
    - name: Clone repo
      uses: actions/checkout@v3
      with:
        repository: "${{ inputs.repository }}"

    - name: Get current date
      shell: bash
      id: date
      run: |
        sudo timedatectl set-timezone Europe/Bratislava
        echo "::set-output name=date::$(date +'%H-%M-%S-%d-%m-%Y')"

    - name: Install dependencies
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y texlive \
        texlive-plain-generic \
        texlive-latex-extra \
        texlive-lang-czechslovak \
        texlive-lang-greek \
        texlive-font-utils \
        lmodern \
        texlive-base \
        latexmk

    - name: Build pdfs
      shell: bash
      run: |
        latexmk -pdf ${{ inputs.file_name }}.tex

    - name: Create release and upload pdf
      id: create_release_upload_pdf
      uses: softprops/actions-gh-release@v2 
      with:
        name: ${{ steps.date.outputs.date }}
        tag_name: ${{ steps.date.outputs.date }}
        body: |
          Release for ${{ steps.date.outputs.date }}
        files: ./${{ inputs.file_name }}.pdf
        draft: false
        prerelease: false
        repository: ${{ inputs.repository }}
        token: ${{ inputs.github_token}}
