name: create-time-release
description: Create a release named after the current time

outputs:
  release_url:
    description: Release url
    value: ${{ steps.create_release.outputs.upload_url }}

inputs:
  github_token:
    description: GitHub token
    required: true

runs:
  using: "composite"

  steps:
    - name: Get current date
      shell: bash
      id: date
      run: |
        sudo timedatectl set-timezone Europe/Bratislava
        echo "::set-output name=date::$(date +'%H-%M-%S-%d-%m-%Y')"

    - name: Create release for build
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        tag_name: ${{ steps.date.outputs.date }}
        release_name: ${{ steps.date.outputs.date }}
        body: |
          Release for ${{ steps.date.outputs.date }}
        draft: false
        prerelease: false
